name: CI - build and test

on:                                
  push:
    branches: [ main ]

jobs:
  build:                           

    runs-on: ubuntu-latest         

    steps:    
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2        
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew              
    - name: Build
      run: ./gradelew build
    - name: copy reports into target folder
      run: ./gradelew deployReports
    - name: deploy reports to website
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with: 
        branch: gh-pages
        folder: build/tmp/website
        clean: false